[package]
name = "rust-scripts"
version = "0.1.0"
authors = ["Svend Sorensen <svend@svends.net>"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
clap = "2.33.0"
lazy_static = "1.4.0"
rand = "0.7.3"
regex = "1.3.3"
structopt = "0.3.8"
tabwriter = "1.2.1"
